repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        name: flake8 (SeedTest API only)
        additional_dependencies: []
        files: ^apps/seedtest_api/.*\.py$

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        name: mypy (SeedTest API only)
        args:
          - --config-file=apps/seedtest_api/mypy.ini
        additional_dependencies: []
        files: ^apps/seedtest_api/.*\.py$
