# Sourcery configuration for DreamSeedAI
# Minimal config - uses Sourcery defaults

rules: []

# Ignore Pylance import resolution errors (false positives)
python:
  version: "3.11"

# Don't block on import resolution issues
refactoring:
  skip_default_rules: []
  
# Quality gate settings
metrics:
  quality_threshold: 25.0


