version: '3.8'

services:
  # DreamSeed API 서버
  dreamseed-api:
    build: .
    container_name: dreamseed-api
    ports:
      - "8002:8002"
    environment:
      - PORT=8002
      - ENVIRONMENT=production
      - REDIS_URL=redis://redis:6379
      - DB_PATH=/app/data/dreamseed_analytics.db
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      - redis
      - prometheus
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - dreamseed-network

  # Redis 캐시 서버
  redis:
    image: redis:7-alpine
    container_name: dreamseed-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - dreamseed-network

  # Prometheus 메트릭 수집
  prometheus:
    image: prom/prometheus:latest
    container_name: dreamseed-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./dreamseed_rules.yml:/etc/prometheus/dreamseed_rules.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    networks:
      - dreamseed-network

  # Node Exporter (시스템 메트릭)
  node-exporter:
    image: prom/node-exporter:latest
    container_name: dreamseed-node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    networks:
      - dreamseed-network

  # Grafana 대시보드
  grafana:
    image: grafana/grafana:latest
    container_name: dreamseed-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped
    depends_on:
      - prometheus
    networks:
      - dreamseed-network

  # Nginx 리버스 프록시
  nginx:
    image: nginx:alpine
    container_name: dreamseed-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - dreamseed-api
    restart: unless-stopped
    networks:
      - dreamseed-network

  # 로그 수집 (Fluentd)
  fluentd:
    image: fluent/fluentd:v1.16-debian-1
    container_name: dreamseed-fluentd
    volumes:
      - ./fluent.conf:/fluentd/etc/fluent.conf
      - ./logs:/var/log/dreamseed
    ports:
      - "24224:24224"
    restart: unless-stopped
    networks:
      - dreamseed-network

volumes:
  redis_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

networks:
  dreamseed-network:
    driver: bridge