---
# =============================
# Alert Threader Deployment Test Playbook
# =============================
# 배포된 환경변수 시스템을 테스트합니다.

- name: Test Alert Threader Environment Deployment
  hosts: all
  become: true
  gather_facts: true
  
  tasks:
    - name: Display test information
      debug:
        msg: |
          =============================
          Alert Threader Environment Test
          =============================
          Target: {{ inventory_hostname }}
          Mode: {{ threader_mode }}
          Environment File: {{ threader_env_path }}
          =============================

    - name: Test environment file existence
      stat:
        path: "{{ threader_env_path }}"
      register: env_file_test

    - name: Display environment file test result
      debug:
        msg: "Environment file test: {{ 'PASSED' if env_file_test.stat.exists else 'FAILED' }}"

    - name: Test environment file permissions
      when: env_file_test.stat.exists
      stat:
        path: "{{ threader_env_path }}"
      register: env_file_perms

    - name: Display environment file permissions
      when: env_file_test.stat.exists
      debug:
        msg: |
          Environment file permissions:
          - Owner: {{ env_file_perms.stat.pw_name }}
          - Group: {{ env_file_perms.stat.gr_name }}
          - Mode: {{ env_file_perms.stat.mode }}

    - name: Test environment file content
      when: env_file_test.stat.exists
      block:
        - name: Check for required variables
          become: true
          command: grep -q "{{ item }}=" "{{ threader_env_path }}"
          register: var_check
          failed_when: false
          loop:
            - SLACK_BOT_TOKEN
            - SLACK_CHANNEL
            - ENVIRONMENT
            - THREAD_STORE

        - name: Display variable check results
          debug:
            msg: |
              Variable check results:
              {% for result in var_check.results %}
              - {{ result.item }}: {{ 'PASSED' if result.rc == 0 else 'FAILED' }}
              {% endfor %}

        - name: Show environment file contents
          become: true
          command: cat "{{ threader_env_path }}"
          register: env_file_contents
          changed_when: false

        - name: Display environment file contents
          debug:
            msg: "{{ env_file_contents.stdout_lines }}"

    - name: Test SOPS functionality (SOPS mode only)
      when: threader_mode == 'sops'
      block:
        - name: Check SOPS binary
          command: sops --version
          register: sops_version
          failed_when: false

        - name: Display SOPS version
          debug:
            msg: "SOPS version: {{ sops_version.stdout if sops_version.rc == 0 else 'not available' }}"

        - name: Test SOPS decryption
          become: true
          command: /usr/local/sbin/alert-threader-sops-decrypt "{{ sops_env_enc }}"
          register: sops_test
          failed_when: false

        - name: Display SOPS test result
          debug:
            msg: "SOPS decryption test: {{ 'PASSED' if sops_test.rc == 0 else 'FAILED' }}"

    - name: Test Vault functionality (Vault mode only)
      when: threader_mode == 'vault'
      block:
        - name: Check Vault binary
          command: vault version
          register: vault_version
          failed_when: false

        - name: Display Vault version
          debug:
            msg: "Vault version: {{ vault_version.stdout if vault_version.rc == 0 else 'not available' }}"

        - name: Check Vault Agent service
          become: true
          systemd:
            name: vault-agent-alert-threader
          register: vault_agent_test

        - name: Display Vault Agent status
          debug:
            msg: "Vault Agent status: {{ vault_agent_test.status.ActiveState }}"

        - name: Test Vault connectivity
          uri:
            url: "{{ vault_addr }}/v1/sys/health"
            method: GET
            status_code: 200, 429, 472, 503
          register: vault_health_test
          failed_when: false

        - name: Display Vault connectivity test result
          debug:
            msg: "Vault connectivity test: {{ 'PASSED' if vault_health_test.status == 200 else 'FAILED' }}"

    - name: Test service integration
      block:
        - name: Check if any Alert Threader services are running
          become: true
          systemd:
            name: "{{ item }}"
          register: service_test
          failed_when: false
          loop:
            - alert-threader-python
            - alert-threader-node
            - alert-threader-go

        - name: Display service test results
          debug:
            msg: |
              Service test results:
              {% for result in service_test.results %}
              - {{ result.item }}: {{ result.status.ActiveState if result.status is defined else 'not found' }}
              {% endfor %}

    - name: Display test summary
      debug:
        msg: |
          =============================
          Test Summary
          =============================
          Environment File: {{ 'PASSED' if env_file_test.stat.exists else 'FAILED' }}
          Mode: {{ threader_mode }}
          {% if threader_mode == 'sops' %}
          SOPS: {{ 'PASSED' if sops_test.rc == 0 else 'FAILED' }}
          {% else %}
          Vault Agent: {{ 'PASSED' if vault_agent_test.status.ActiveState == 'active' else 'FAILED' }}
          {% endif %}
          =============================
