"""content audit log table

Revision ID: b517600fb8bb
Revises: 7a3805fbeab4
Create Date: 2025-09-25 00:35:58.607981

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b517600fb8bb"
down_revision: Union[str, None] = "7a3805fbeab4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stripe_webhook_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.String(length=64), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("customer_id", sa.String(length=64), nullable=True),
        sa.Column("subscription_id", sa.String(length=64), nullable=True),
        sa.Column("idempotency_key", sa.String(length=64), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("amount_total", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=8), nullable=True),
        sa.Column("livemode", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("status", sa.String(length=32), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_stripe_webhook_events_customer_id"),
        "stripe_webhook_events",
        ["customer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stripe_webhook_events_event_id"),
        "stripe_webhook_events",
        ["event_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_stripe_webhook_events_idempotency_key"),
        "stripe_webhook_events",
        ["idempotency_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stripe_webhook_events_request_id"),
        "stripe_webhook_events",
        ["request_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stripe_webhook_events_subscription_id"),
        "stripe_webhook_events",
        ["subscription_id"],
        unique=False,
    )
    op.alter_column(
        "attempts",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
    )
    op.drop_index(
        "ix_attempts_response_gin", table_name="attempts", postgresql_using="gin"
    )
    op.alter_column(
        "content",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
    )
    op.alter_column(
        "content",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
    )
    op.drop_index("ix_content_doc_gin", table_name="content", postgresql_using="gin")
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
    )
    op.add_column(
        "users_profile",
        sa.Column("stripe_customer_id", sa.String(length=64), nullable=True),
    )
    op.create_index(
        op.f("ix_users_profile_stripe_customer_id"),
        "users_profile",
        ["stripe_customer_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_users_profile_stripe_customer_id"), table_name="users_profile"
    )
    op.drop_column("users_profile", "stripe_customer_id")
    op.alter_column(
        "users",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
    )
    op.create_index(
        "ix_content_doc_gin", "content", ["doc"], unique=False, postgresql_using="gin"
    )
    op.alter_column(
        "content",
        "updated_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "content",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
    )
    op.create_index(
        "ix_attempts_response_gin",
        "attempts",
        ["response"],
        unique=False,
        postgresql_using="gin",
    )
    op.alter_column(
        "attempts",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
    )
    op.drop_index(
        op.f("ix_stripe_webhook_events_subscription_id"),
        table_name="stripe_webhook_events",
    )
    op.drop_index(
        op.f("ix_stripe_webhook_events_request_id"), table_name="stripe_webhook_events"
    )
    op.drop_index(
        op.f("ix_stripe_webhook_events_idempotency_key"),
        table_name="stripe_webhook_events",
    )
    op.drop_index(
        op.f("ix_stripe_webhook_events_event_id"), table_name="stripe_webhook_events"
    )
    op.drop_index(
        op.f("ix_stripe_webhook_events_customer_id"), table_name="stripe_webhook_events"
    )
    op.drop_table("stripe_webhook_events")
    # ### end Alembic commands ###
