"""add soft delete to content

Revision ID: 1609e6a72b5e
Revises: 22a98eff6794
Create Date: 2025-09-25 01:27:11.628895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1609e6a72b5e'
down_revision: Union[str, None] = '22a98eff6794'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_profile', sa.Column('stripe_subscription_id', sa.String(length=64), nullable=True))
    op.add_column('users_profile', sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users_profile', sa.Column('cancel_at_period_end', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users_profile', sa.Column('status', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_users_profile_stripe_subscription_id'), 'users_profile', ['stripe_subscription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_profile_stripe_subscription_id'), table_name='users_profile')
    op.drop_column('users_profile', 'status')
    op.drop_column('users_profile', 'cancel_at_period_end')
    op.drop_column('users_profile', 'current_period_end')
    op.drop_column('users_profile', 'stripe_subscription_id')
    # ### end Alembic commands ###
