"""extend users_profile with subscription fields

Revision ID: 22a98eff6794
Revises: ee8f940d61f4
Create Date: 2025-09-25 00:45:37.499745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22a98eff6794'
down_revision: Union[str, None] = 'ee8f940d61f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_audit_log_action'), 'content_audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_content_audit_log_content_id'), 'content_audit_log', ['content_id'], unique=False)
    op.create_index(op.f('ix_content_audit_log_user_id'), 'content_audit_log', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_audit_log_user_id'), table_name='content_audit_log')
    op.drop_index(op.f('ix_content_audit_log_content_id'), table_name='content_audit_log')
    op.drop_index(op.f('ix_content_audit_log_action'), table_name='content_audit_log')
    op.drop_table('content_audit_log')
    # ### end Alembic commands ###
