apiVersion: v1
kind: Service
metadata:
  name: seedtest-api
  labels:
    app: seedtest-api
spec:
  type: ClusterIP
  selector:
    app: seedtest-api
  ports:
    - name: http
      port: 80
      targetPort: http
