name: portal_api_ci

on:
  push:
    paths:
      - "portal_api/**"
  pull_request:
    paths:
      - "portal_api/**"

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: dreamseed
        ports: ["5432:5432"]
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 20

      redis:
        image: redis:7
        ports: ["6379:6379"]
        options: >-
          --health-cmd "redis-cli ping || exit 1"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 20

    steps:
      - uses: actions/checkout@v4

      - name: Install OS deps for WeasyPrint
        run: |
          sudo apt-get update
          sudo apt-get install -y libcairo2 libpango-1.0-0 libpangoft2-1.0-0 libffi8 libglib2.0-0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        working-directory: portal_api
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt || true
          pip install pytest httpx pytest-asyncio uvicorn

      - name: Env & Alembic
        working-directory: portal_api
        env:
          DATABASE_URL: postgresql+psycopg://postgres:postgres@localhost:5432/dreamseed
          JWT_SECRET: testsecret
          REDIS_URL: redis://localhost:6379/0
        run: |
          source .venv/bin/activate
          alembic upgrade head

      - name: Run tests
        working-directory: portal_api
        env:
          DATABASE_URL: postgresql+psycopg://postgres:postgres@localhost:5432/dreamseed
          JWT_SECRET: testsecret
          REDIS_URL: redis://localhost:6379/0
        run: |
          source .venv/bin/activate
          pytest -q
