name: build-seedtest-api

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/seedtest_api/**'
      - '.github/workflows/build-seedtest-api.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      REGION: asia-northeast3
      PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
      REPO: seedtest
      IMAGE: seedtest-api
    steps:
      - uses: actions/checkout@v4

      # GCP OIDC 로그인 (WIF)
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.GCP_WIF_PROVIDER }}
          service_account: ${{ vars.GCP_WIF_SERVICE_ACCOUNT }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to Artifact Registry
        run: |
          gcloud auth configure-docker $REGION-docker.pkg.dev --quiet

      - name: Compute image ref
        id: compute
        run: |
          IMAGE_REF="${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO}/${IMAGE}"
          echo "image_ref=${IMAGE_REF}" >> "$GITHUB_OUTPUT"

      # 빌드 캐시 (GitHub Actions Cache 사용)
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.ref }}-${{ hashFiles('apps/seedtest_api/**/Dockerfile','apps/seedtest_api/**/requirements*.txt','apps/seedtest_api/**/package*.json') }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ github.ref }}-
            ${{ runner.os }}-buildx-

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: apps/seedtest_api
          push: true
          tags: |
            ${{ steps.compute.outputs.image_ref }}:sha-${{ github.sha }}
            ${{ steps.compute.outputs.image_ref }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          provenance: false

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Output image
        run: echo "IMAGE=${{ steps.compute.outputs.image_ref }}:sha-${GITHUB_SHA}" >> $GITHUB_OUTPUT

