name: Build (push)

on:
  push:
    branches: [ main, develop ]

permissions:
  contents: read

concurrency:
  group: build-on-push-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Validate build can package or compile
        run: |
          if [ -f setup.py ] || [ -f pyproject.toml ]; then
            python -m pip install --upgrade pip build
            python -m build --sdist --wheel || true
          fi
          python -m compileall -q .
