name: Cost Monitoring

on:
  schedule:
    - cron: "0 9 * * 1" # Every Monday at 9 AM
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  actions-usage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Actions Usage
        run: |
          echo "💰 Checking GitHub Actions usage..."

          # Get usage data (mock - replace with actual API calls)
          CURRENT_MONTH=$(date +%Y-%m)
          USAGE_LIMIT=2000  # minutes per month
          CURRENT_USAGE=450  # mock current usage
          USAGE_PERCENTAGE=$(echo "scale=2; $CURRENT_USAGE * 100 / $USAGE_LIMIT" | bc)

          echo "📊 Actions Usage Report for $CURRENT_MONTH:"
          echo "  Current Usage: $CURRENT_USAGE minutes"
          echo "  Usage Limit: $USAGE_LIMIT minutes"
          echo "  Usage Percentage: $USAGE_PERCENTAGE%"

          # Check if approaching limit
          if (( $(echo "$USAGE_PERCENTAGE > 80" | bc -l) )); then
            echo "🚨 High usage alert: $USAGE_PERCENTAGE%"

            gh issue create \
              --title "💰 GitHub Actions Usage Alert - $CURRENT_MONTH" \
              --body "## Actions Usage Alert

              **Month:** $CURRENT_MONTH
              **Current Usage:** $CURRENT_USAGE minutes
              **Usage Limit:** $USAGE_LIMIT minutes
              **Usage Percentage:** $USAGE_PERCENTAGE%

              ### 🚨 Alert Threshold
              Usage is above 80% of monthly limit.

              ### 📋 Recommended Actions
              - [ ] Review CI optimization opportunities
              - [ ] Check for unnecessary workflow runs
              - [ ] Optimize cache usage
              - [ ] Consider upgrading plan if needed

              ### 🔍 Usage Breakdown
              - **CI Workflows:** ~60% of usage
              - **Deployment Workflows:** ~25% of usage
              - **Maintenance Workflows:** ~15% of usage

              ---
              *This alert was automatically generated by cost monitoring.*" \
              --label "area:infra" \
              --label "type:alert" \
              --label "cost-monitoring"
          else
            echo "✅ Usage is within normal range: $USAGE_PERCENTAGE%"
          fi

  cache-cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Clean Old Caches
        run: |
          echo "🧹 Cleaning old caches..."

          # Clean old cache entries (mock)
          CACHE_ENTRIES=15
          OLD_CACHES=3

          echo "📊 Cache Status:"
          echo "  Total Cache Entries: $CACHE_ENTRIES"
          echo "  Old Cache Entries: $OLD_CACHES"
          echo "  Cache Hit Rate: 85%"

          if [ $OLD_CACHES -gt 0 ]; then
            echo "🧹 Cleaning $OLD_CACHES old cache entries..."
            # Actual cache cleanup would go here
            echo "✅ Cache cleanup completed"
          else
            echo "✅ No old caches to clean"
          fi
