name: Examinee Frontend - Unit Tests

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'apps/examinee-frontend/**'
      - '.github/workflows/examinee-frontend-unit.yml'
  pull_request:
    paths:
      - 'apps/examinee-frontend/**'
      - '.github/workflows/examinee-frontend-unit.yml'

permissions:
  contents: read

jobs:
  lint-a11y:
    name: ESLint a11y Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/examinee-frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile=false

      - name: Run ESLint (jsx-a11y)
        run: pnpm run lint

  unit-tests:
    name: Unit Tests (Vitest)
    runs-on: ubuntu-latest
    needs: lint-a11y
    defaults:
      run:
        working-directory: apps/examinee-frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile=false

      - name: Run unit tests (Vitest)
        run: pnpm run test:ci
        env:
          # Ensure tests run with JSDOM and without Next build time variables
          CI: 'true'

      - name: Upload coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: examinee-frontend-coverage
          path: apps/examinee-frontend/coverage/**

  next-build:
    name: Next Build
    runs-on: ubuntu-latest
    needs: unit-tests
    defaults:
      run:
        working-directory: apps/examinee-frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile=false

      - name: Build (Next.js)
        run: pnpm run build
        env:
          NEXT_TELEMETRY_DISABLED: '1'
          CI: 'true'

  storybook-build:
    name: Storybook Build
    runs-on: ubuntu-latest
    needs: unit-tests
    defaults:
      run:
        working-directory: apps/examinee-frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Debug pnpm path/version
        run: |
          echo "Node: $(node -v)"
          echo "PNPM: $(pnpm -v)"
          which pnpm || true
          pnpm config get store-dir || true

      - name: Ensure pnpm present
        run: |
          if ! command -v pnpm >/dev/null 2>&1; then
            echo "pnpm missing on PATH" && exit 1
          fi

      - name: Install dependencies
        run: pnpm install --frozen-lockfile=false

      - name: Build Storybook
        run: pnpm run build-storybook

      - name: Upload Storybook static
        uses: actions/upload-artifact@v4
        with:
          name: examinee-frontend-storybook
          path: apps/examinee-frontend/storybook-static/**

  a11y-smoke:
    name: Accessibility Smoke (Playwright + axe)
    runs-on: ubuntu-latest
    needs: next-build
    defaults:
      run:
        working-directory: apps/examinee-frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Setup pnpm
        run: |
          corepack enable
          corepack prepare pnpm@9 --activate

      - name: Install dependencies
        run: pnpm install --frozen-lockfile=false

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Run a11y smoke test
        run: pnpm run test:a11y
        env:
          NEXT_TELEMETRY_DISABLED: '1'
          CI: 'true'
