name: Close Stale Issues and PRs

on:
  schedule:
    - cron: "0 2 * * *"  # 매일 02:00 UTC
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Mark stale issues and PRs
        uses: actions/stale@v9
        with:
          # Configuration for Issues
          days-before-stale: 60
          days-before-close: 14
          stale-issue-label: "stale"
          stale-issue-message: |
            This issue has been automatically marked as stale because it has not had recent activity.

            It will be closed in 14 days if no further activity occurs.

            If you believe this issue should remain open, please:
            - Add a comment explaining why
            - Add the `keep-open` label
            - Or simply add any new activity

            Thank you for your contribution! 🙏
          close-issue-label: "closed-by-stale"
          close-issue-message: |
            This issue has been automatically closed due to inactivity.

            If you believe this issue should be reopened, please:
            - Create a new issue with the same details
            - Reference this closed issue
            - Add the `reopen` label if applicable

            Thank you for your understanding! 🙏

          # Configuration for PRs
          days-before-stale-pr: 30
          days-before-close-pr: 7
          stale-pr-label: "stale"
          stale-pr-message: |
            This pull request has been automatically marked as stale because it has not had recent activity.

            It will be closed in 7 days if no further activity occurs.

            If you believe this PR should remain open, please:
            - Add a comment explaining the status
            - Add the `keep-open` label
            - Or simply add any new activity (commits, reviews, etc.)

            Thank you for your contribution! 🙏
          close-pr-label: "closed-by-stale"
          close-pr-message: |
            This pull request has been automatically closed due to inactivity.

            If you believe this PR should be reopened, please:
            - Create a new PR with the same changes
            - Reference this closed PR
            - Add the `reopen` label if applicable

            Thank you for your understanding! 🙏

          # Exemptions (items with these labels will not be marked as stale)
          exempt-issue-labels: |
            security,
            priority:critical,
            priority:high,
            keep-open,
            area:security,
            type:bug
          exempt-pr-labels: |
            security,
            priority:critical,
            priority:high,
            keep-open,
            area:security,
            automerge,
            status:in-progress

          # Performance settings
          operations-per-run: 200
          remove-stale-when-updated: true
          remove-stale-pr-when-updated: true

          # Repository settings
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          debug-only: false
