apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: seedtest-api-jwt
  namespace: seedtest
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gsm-seedtest
  target:
    name: seedtest-api-jwt
    creationPolicy: Owner
  data:
    - secretKey: JWT_ALGO
      remoteRef:
        key: projects/PROJECT_ID/secrets/JWT_ALGO/versions/latest
    - secretKey: JWT_JWKS_URL
      remoteRef:
        key: projects/PROJECT_ID/secrets/JWT_JWKS_URL/versions/latest
    - secretKey: JWT_ISS
      remoteRef:
        key: projects/PROJECT_ID/secrets/JWT_ISS/versions/latest
    - secretKey: JWT_AUD
      remoteRef:
        key: projects/PROJECT_ID/secrets/JWT_AUD/versions/latest
    - secretKey: JWKS_CACHE_TTL
      remoteRef:
        key: projects/PROJECT_ID/secrets/JWKS_CACHE_TTL/versions/latest
